### ISSUE TITLE
pyopenstates.APIError: Piston/0.2.3rc1 (Django 1.9.13) crash report

### ISSUE THREAD

**Issue by georgezoto** [openstates/pyopenstates#10]
Hello pyopenstates team,

Thank you for maintaining this great service. I ran into the following issue while looking for state legislators in NY state for a list of schools.

Any idea what could be the problem?  My method is pretty simple and actually sleeps for about half a second to overcome and throttling errors. I am only using `pyopenstates.locate_legislators()`

Thank you,
George Zoto

```
from time import sleep

def open_states_api(lat_lng_dict):
    sleep(0.4)
    try:
        if lat_lng_dict and ('lat' in lat_lng_dict) and ('lng' in lat_lng_dict):
            my_fields = ['active', 'chamber', 'district', 'full_name', 'sources', 'email']
            legislators = pyopenstates.locate_legislators(lat=lat_lng_dict['lat'], long=lat_lng_dict['lng'], fields=my_fields)
        
            if legislators:
                if len(legislators) == 2:
                    return (legislators[0]['chamber'], legislators[0]['district'], legislators[0]['full_name'], legislators[0]['email'], legislators[1]['chamber'], legislators[1]['district'], legislators[1]['full_name'], legislators[1]['email'])
                elif len(legislators) == 1:
                    return (legislators[0]['chamber'], legislators[0]['district'], legislators[0]['full_name'], legislators[0]['email'], '', '', '', '')
                
        return ('', '', '', '', '', '', '', '')
        
    except:
        print(traceback.format_exc())
```

```
Traceback (most recent call last):
  File "<ipython-input-172-8f0b54898bab>", line 8, in open_states_api
    legislators = pyopenstates.locate_legislators(lat=lat_lng_dict['lat'], long=lat_lng_dict['lng'], fields=my_fields)
  File "anaconda/lib/python3.6/site-packages/pyopenstates.py", line 316, in locate_legislators
    return _get("/legislators/geo/", params=dict(lat=lat, long=long, fields=fields))
  File "anaconda/lib/python3.6/site-packages/pyopenstates.py", line 102, in _get
    raise APIError(response.text)
    
pyopenstates.APIError: "Piston/0.2.3rc1 (Django 1.9.13) crash report:

Traceback (most recent call last):

  File \"/home/openstates/virt/local/lib/python2.7/site-packages/newrelic/hooks/component_piston.py\", line 33, in __call__
    return self._nr_wrapped(*args, **kwargs)

  File \"/home/openstates/virte51090ea9e0b4384ccb574fcaac07778b0f75996/src/billy/billy/web/api/handlers.py\", line 88, in new_read
    obj = old_read(*args, **kwargs)

  File \"/home/openstates/virte51090ea9e0b4384ccb574fcaac07778b0f75996/src/billy/billy/web/api/handlers.py\", line 396, in read
    resp = json.load(urllib2.urlopen(url, timeout=0.5))

  File \"/usr/lib/python2.7/urllib2.py\", line 154, in urlopen
    return opener.open(url, data, timeout)

  File \"/home/openstates/virt/local/lib/python2.7/site-packages/newrelic/hooks/external_urllib2.py\", line 31, in _nr_wrapper_opener_director_open_
    return wrapped(*args, **kwargs)

  File \"/usr/lib/python2.7/urllib2.py\", line 429, in open
    response = self._open(req, data)

  File \"/usr/lib/python2.7/urllib2.py\", line 447, in _open
    '_open', req)

  File \"/usr/lib/python2.7/urllib2.py\", line 407, in _call_chain
    result = func(*args)

  File \"/usr/lib/python2.7/urllib2.py\", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)

  File \"/usr/lib/python2.7/urllib2.py\", line 1198, in do_open
    raise URLError(err)

URLError: <urlopen error timed out>
"
```

**Comment by seanthegeek** [comment]
Based on `URLError: <urlopen error timed out>`, this looks like a server side issue
